"""
PRISM Platform — Report Generation Service
Generates PDF clinical reports from diagnostic session data.
"""
import io
import logging
from datetime import datetime

logger = logging.getLogger(__name__)


def generate_pdf_report(session_data: dict) -> bytes:
    """Generate a clinical PDF report from diagnostic session data."""
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.units import mm
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.colors import HexColor
    except ImportError:
        logger.warning("reportlab not installed")
        return b"%PDF-1.4 placeholder"

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=20*mm, bottomMargin=20*mm)
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("PRISMTitle", parent=styles["Title"], fontSize=18, textColor=HexColor("#3b82f6"))
    heading_style = ParagraphStyle("PRISMHeading", parent=styles["Heading2"], textColor=HexColor("#1e40af"))
    elements = []

    elements.append(Paragraph("PRISM Diagnostic Report", title_style))
    elements.append(Spacer(1, 10*mm))

    # Primary diagnosis
    primary = session_data.get("primary_diagnosis", "N/A")
    confidence = session_data.get("confidence_score", 0)
    elements.append(Paragraph("Diagnosis", heading_style))
    elements.append(Paragraph(f"<b>{primary}</b> (Confidence: {confidence:.0%})", styles["Normal"]))
    elements.append(Spacer(1, 5*mm))

    # Disease probabilities table
    disease_probs = session_data.get("disease_probabilities", {})
    if disease_probs:
        elements.append(Paragraph("Disease Probabilities", heading_style))
        data = [["Disease", "Probability"]]
        for d, p in sorted(disease_probs.items(), key=lambda x: x[1], reverse=True):
            data.append([d, f"{p:.1%}"])
        t = Table(data)
        t.setStyle(TableStyle([
            ("BACKGROUND", (0,0), (-1,0), HexColor("#3b82f6")),
            ("TEXTCOLOR", (0,0), (-1,0), HexColor("#ffffff")),
            ("GRID", (0,0), (-1,-1), 0.5, HexColor("#e5e7eb")),
        ]))
        elements.append(t)
        elements.append(Spacer(1, 5*mm))

    # Causal narrative
    causal = session_data.get("causal_results", {})
    if causal and causal.get("narrative"):
        elements.append(Paragraph("Causal Explanation", heading_style))
        elements.append(Paragraph(causal["narrative"], styles["Normal"]))

    # Footer
    elements.append(Spacer(1, 10*mm))
    elements.append(Paragraph(
        f"<i>Generated by PRISM on {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}. "
        "This is an AI screening assessment, not a clinical diagnosis.</i>",
        styles["Italic"],
    ))

    doc.build(elements)
    return buffer.getvalue()
